version: '3'
services:
  backend:
    image: khalilbchir/server-side
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./AudiTech-client-side/
      dockerfile: Dockerfile
    ports:
      - "4200:80" 
    depends_on:
      - backend
